var keyMirror = require('keymirror');

module.exports = keyMirror({
    // actions
    HIDOGS_VENDOR_ORDER_VIEW_ORDER_LIST: null,
    HIDOGS_VENDOR_ORDER_GET_ORDER_LIST: null,
    HIDOGS_VENDOR_ORDER_GET_ORDER_LIST_SUCCESS: null,
    HIDOGS_VENDOR_ORDER_GET_ORDER_LIST_FAIL: null,

    PAY_ORDER_FAIL: null,
    PAY_ORDER_SUCCESS: null,


    // states
    VENDOR_ORDER_STORE_STATE_LIST: null,
    VENDOR_ORDER_STORE_STATE_LIST_LOADING: null,
    VENDOR_ORDER_STORE_STATE_ERROR: null,
    VENDOR_ORDER_STORE_STATE_CHECK: null,
    VENDOR_ORDER_STORE_STATE_CHECK_IN_PROGRESS: null,
    VENDOR_ORDER_STORE_STATE_CHECK_SUCCESS: null,
    VENDOR_ORDER_STORE_STATE_CHECK_FAIL: null,
    VENDOR_ORDER_STORE_STATE_CHECK_UPDATE_SUCCESS: null,


});
