var keyMirror = require('keymirror');

module.exports = keyMirror({

    // actions
    ACTION_GET_OPENID_SUCCESS: null,
    ACTION_GET_OPENID_FAIL: null,

    ACTION_GET_VENDOR_PROFILE_SUCCESS: null,
    ACTION_GET_VENDOR_PROFILE_FAIL: null,

    ACTION_UPDATE_VENDOR_PROFILE_FAKE: null,
    ACTION_UPDATE_VENDOR_PROFILE_SUCCESS: null,
    ACTION_UPDATE_VENDOR_PROFILE_FAIL: null,
    ACTION_UPDATE_VENDOR_PROFILE_SHOW: null,

    ACTION_UPLOAD_PIC_SUCCESS: null,
    ACTION_UPLOAD_PIC_FAIL: null,
    ACTION_REMOVE_PIC: null,

    ACTION_CANCEL_PROFILE_EDIT: null,
    ACTION_TRIGGER_PROFILE_EDIT: null,

    ACTION_SHOW_PROFILE_VERIFY_MSG: null,

    ACTION_SHOW_AGREEMENT: null,
    ACTION_CLOSE_AGREEMENT: null,

    ACTION_GET_WX_SIGNATURE_SUCCESS: null,
    ACTION_GET_WX_SIGNATURE_FAIL: null,

    ACTION_GET_WX_MEDIA_SUCCESS: null,
    ACTION_GET_WX_MEDIA_FAIL: null,



    // states
    STATE_VENDOR_APPLICAITON_LOADING : null,
    STATE_VENDOR_APPLICAITON_DRAFT : null,
    STATE_VENDOR_APPLICAITON_EDITING : null,
    STATE_VENDOR_APPLICAITON_CREATED : null,
    STATE_VENDOR_APPLICAITON_REVIEWING : null,
    STATE_VENDOR_APPLICAITON_REJECT : null,
    STATE_VENDOR_APPLICAITON_APPROVED : null,
    STATE_VENDOR_APPLICAITON_EDIT_AGREEMENT : null,
    STATE_VENDOR_APPLICAITON_PROFILE_AGREEMENT : null,

    STATE_FAIL : null,


});
