var keyMirror = require('keymirror');

module.exports = keyMirror({
    // actions
    PAY_ORDER: null,
    PAY_ORDER_SUCCESS: null,
    PAY_ORDER_FAIL: null,

    ACTION_PRODUCT_TO_COMMENT: null,
    ACTION_PRODUCT_TO_AVAILABILITY: null,
    ACTION_PRODUCT_TO_ORDER_CREATION: null,
    ACTION_PRODUCT_TO_VENDOR: null,
    ACTION_PRODUCT_TO_EXIT_POLICY: null,
    ACTION_PRODUCT_LOAD_PRODUCT_SUCCESSFUL: null,
    ACTION_PRODUCT_LOAD_PRODUCT_FAIL: null,
    ACTION_PRODUCT_LOAD_VENDOR_SUCCESSFUL: null,
    ACTION_PRODUCT_LOAD_VENDOR_FAIL: null,
    ACTION_PRODUCT_LOAD_META_SUCCESSFUL: null,
    ACTION_PRODUCT_LOAD_META_FAIL: null,
    ACTION_PRODUCT_FAV_FAKE: null,
    ACTION_PRODUCT_FAV_SUCCESSFUL: null,
    ACTION_PRODUCT_FAV_FAIL: null,
    ACTION_PRODUCT_LOAD_USER_SUCCESSFUL: null,
    ACTION_PRODUCT_LOAD_USER_FAIL: null,

    ACTION_COMMENT_TO_PRODUCT: null,
    ACTION_COMMENT_LOAD_COMMENT_SUCCSSFUL: null,
    ACTION_COMMENT_LOAD_COMMENT_FAIL: null,

    ACTION_AVAILABILITY_TO_PRODUCT: null,
    ACTION_AVAILABILITY_LOAD_SUCCSSFUL: null,
    ACTION_AVAILABILITY_LOAD_FAIL: null,

    ACTION_ORDER_REDIRECT_TO_ORDER_CREATION: null,

    ACTION_EXIT_POLICY_TO_PRODUCT: null,

    // states
    STATE_PRODUCT: null,
    STATE_AVAILABILITY: null,
    STATE_COMMENT: null,
    STATE_EXIT_POLICY: null,


});
