var keyMirror = require('keymirror');

module.exports = keyMirror({
    HIDOGS_GET_LOCATION: null,
    HIDOGS_CREATE_ORDER: null,
    HIDOGS_GET_INIT_LOCATION: null,
    HIDOGS_GET_SHOP: null,

    // Web Utilities
    WEB_UTILS_REQUEST_TIMEOUT: null,
    WEB_UTILS_REQUEST_ERROR: null,
    WEB_UTILS_REQUEST_NOT_FOUND: null,

    // Vendor Product
    HIDOGS_VENDOR_PRODUCT_VIEW_PRODUCT_LIST: null,
    HIDOGS_VENDOR_PRODUCT_GET_PRODUCT_LIST: null,
    HIDOGS_VENDOR_PRODUCT_GET_PRODUCT_LIST_SUCCESS: null,
    HIDOGS_VENDOR_PRODUCT_GET_PRODUCT_LIST_FAIL: null,

    HIDOGS_VENDOR_PRODUCT_VIEW_PRODUCT: null,
    HIDOGS_VENDOR_PRODUCT_GET_PRODUCT_SUCCESS: null,
    HIDOGS_VENDOR_PRODUCT_GET_PRODUCT_FAIL: null,

    HIDOGS_VENDOR_PRODUCT_VIEW_PRODUCT_NEW: null,
    HIDOGS_VENDOR_PRODUCT_NEW_PRODUCT: null,
    HIDOGS_VENDOR_PRODUCT_NEW_PRODUCT_SUCCESS: null,
    HIDOGS_VENDOR_PRODUCT_NEW_PRODUCT_FAIL: null,

    HIDOGS_VENDOR_PRODUCT_VIEW_PRODUCT_DELETE: null,
    HIDOGS_VENDOR_PRODUCT_DELETE_PRODUCT: null,
    HIDOGS_VENDOR_PRODUCT_DELETE_PRODUCT_SUCCESS: null,
    HIDOGS_VENDOR_PRODUCT_DELETE_PRODUCT_FAIL: null,

    HIDOGS_VENDOR_PRODUCT_VIEW_PRODUCT_EDIT: null,
    HIDOGS_VENDOR_PRODUCT_EDIT_PRODUCT: null,
    HIDOGS_VENDOR_PRODUCT_EDIT_PRODUCT_SUCCESS: null,
    HIDOGS_VENDOR_PRODUCT_EDIT_PRODUCT_FAIL: null
});
