var vendor = [
    {
        "_id": "1",
        "name": "Misty",
        "nick_name": "Luna",
        "pwd": 552619,
        "email": "lunabutler@portica.com",
        "mobile": "+86 (902) 586-3319",
        "wechat_openid": 585,
        "wechat_nickname": "Mullins",
        "gender": "male",
        "age": "<SyntaxError: Unexpected token .>",
        "province": "广东",
        "city": "广州",
        "region": "番禺",
        "country": "CN",
        "address": "729 Kosciusko Street, Roeville, Wyoming, 7612",
        "latitude": 51.028985,
        "longitude": 31.781447,
        "head_image_url": "http://placehold.it/32x32",
        "alipayaccount": "mullinsbutler@portica.com",
        "isactive": true,
        "created_time": "Wed Oct 21 2015 11:05:24 GMT+0800 (CST)",
        "modified_time": "Fri Oct 30 2015 09:16:49 GMT+0800 (CST)"
    },
    {
        "_id": "2",
        "name": "Sophie",
        "nick_name": "Felecia",
        "pwd": 841575,
        "email": "feleciabutler@portica.com",
        "mobile": "+86 (804) 572-3591",
        "wechat_openid": 981,
        "wechat_nickname": "Fernandez",
        "gender": "male",
        "age": "<SyntaxError: Unexpected token .>",
        "province": "广东",
        "city": "广州",
        "region": "番禺",
        "country": "CN",
        "address": "529 Kenmore Court, Calvary, Montana, 3543",
        "latitude": 62.924175,
        "longitude": 81.853181,
        "head_image_url": "http://placehold.it/32x32",
        "alipayaccount": "fernandezbutler@portica.com",
        "isactive": false,
        "created_time": "Sun Oct 25 2015 08:11:22 GMT+0800 (CST)",
        "modified_time": "Thu Oct 15 2015 23:56:25 GMT+0800 (CST)"
    },
    {
        "_id": "3",
        "name": "Elsa",
        "nick_name": "Alston",
        "pwd": 947471,
        "email": "alstonbutler@portica.com",
        "mobile": "+86 (991) 529-2384",
        "wechat_openid": 584,
        "wechat_nickname": "Rivera",
        "gender": "male",
        "age": "<SyntaxError: Unexpected token .>",
        "province": "广东",
        "city": "广州",
        "region": "番禺",
        "country": "CN",
        "address": "524 Gain Court, Belgreen, Delaware, 444",
        "latitude": -19.072796,
        "longitude": -61.490764,
        "head_image_url": "http://placehold.it/32x32",
        "alipayaccount": "riverabutler@portica.com",
        "isactive": false,
        "created_time": "Fri Oct 23 2015 19:58:06 GMT+0800 (CST)",
        "modified_time": "Thu Oct 29 2015 05:12:26 GMT+0800 (CST)"
    },
    {
        "_id": "4",
        "name": "Roxie",
        "nick_name": "Clare",
        "pwd": 856406,
        "email": "clarebutler@portica.com",
        "mobile": "+86 (841) 578-3395",
        "wechat_openid": 411,
        "wechat_nickname": "Brittney",
        "gender": "female",
        "age": "<SyntaxError: Unexpected token .>",
        "province": "广东",
        "city": "广州",
        "region": "番禺",
        "country": "CN",
        "address": "822 Olive Street, Wiscon, Rhode Island, 6000",
        "latitude": -13.474536,
        "longitude": -19.790579,
        "head_image_url": "http://placehold.it/32x32",
        "alipayaccount": "brittneybutler@portica.com",
        "isactive": true,
        "created_time": "Thu Oct 15 2015 18:31:21 GMT+0800 (CST)",
        "modified_time": "Sun Oct 18 2015 17:05:33 GMT+0800 (CST)"
    },
    {
        "_id": "5",
        "name": "Workman",
        "nick_name": "Susanna",
        "pwd": 727261,
        "email": "susannabutler@portica.com",
        "mobile": "+86 (995) 537-2971",
        "wechat_openid": 259,
        "wechat_nickname": "Heath",
        "gender": "male",
        "age": "<SyntaxError: Unexpected token .>",
        "province": "广东",
        "city": "广州",
        "region": "海珠",
        "country": "CN",
        "address": "416 Columbia Street, Whitewater, Pennsylvania, 1257",
        "latitude": -2.679272,
        "longitude": 6.833481,
        "head_image_url": "http://placehold.it/32x32",
        "alipayaccount": "heathbutler@portica.com",
        "isactive": false,
        "created_time": "Sat Oct 31 2015 11:17:36 GMT+0800 (CST)",
        "modified_time": "Fri Oct 23 2015 04:51:08 GMT+0800 (CST)"
    }
]




module.exports = vendor;