var keyMirror = require('keymirror');

module.exports = keyMirror({
    // actions
    INIT_LOAD_VENDOR_SUCCESSFUL: null,
    INIT_LOAD_PRODUCT_LIST_SUCCESSFUL: null,
    INIT_FAIL:null,

    ACTION_PRODUCT_FAV_FAKE: null,
    ACTION_PRODUCT_FAV_SUCCESSFUL: null,
    ACTION_PRODUCT_FAV_FAIL: null,

    ACTION_PRODUCT_LOAD_USER_SUCCESSFUL: null,
    ACTION_PRODUCT_LOAD_USER_FAIL: null,

    ACTION_TRIGGER_COMMENT_FROM_MAIN: null,
    ACTION_TRIGGER_MAIN_FROM_COMMENT: null,
    ACTION_LOAD_COMMENT_SUCCESSFUL: null,
    ACTION_LOAD_COMMENT_FAIL: null,

    // states
    STATE_VENDOR_PAGE: null,
    STATE_COMMENT: null,

});
