var keyMirror = require('keymirror');

module.exports = keyMirror({
    // actions
    ACTION_VENDOR_PRODUCT_LIST_TRIGGER_DETAIL: null,
    ACTION_VENDOR_PRODUCT_LIST_TRIGGER_SETTING: null,
    ACTION_VENDOR_PRODUCT_LIST_TRIGGER_NEW: null,

    ACTION_VENDOR_PRODUCT_DETAIL_TRIGGER_LIST: null,
    ACTION_VENDOR_PRODUCT_DETAIL_TRIGGER_EDIT: null,
    ACTION_VENDOR_PRODUCT_DETAIL_TRIGGER_PREVIEW: null,
    ACTION_VENDOR_PRODUCT_DETAIL_TRIGGER_COMMENT: null,

    ACTION_VENDOR_PRODUCT_COMMENT_TRIGGER_DETAIL: null,

    ACTION_VENDOR_PRODUCT_SETTING_TRIGGER_SETTING_EDIT: null,
    ACTION_VENDOR_PRODUCT_SETTING_TRIGGER_LIST: null,

    ACTION_VENDOR_PRODUCT_SETTING_EDIT_SAVE_TRIGGER_SETTING: null,
    ACTION_VENDOR_PRODUCT_SETTING_EDIT_CANCEL_TRIGGER_SETTING: null,

    ACTION_VENDOR_PRODUCT_NEW_SAVE_TRIGGER_LIST: null,
    ACTION_VENDOR_PRODUCT_NEW_SAVE_DATA_SUCCESS: null,
    ACTION_VENDOR_PRODUCT_NEW_SAVE_DATA_FAIL: null,
    ACTION_VENDOR_PRODUCT_NEW_CANCEL_TRIGGER_LIST: null,

    ACTION_VENDOR_PRODUCT_EDIT_SAVE_TRIGGER_DETAIL: null,
    ACTION_VENDOR_PRODUCT_EDIT_CANCEL_TRIGGER_DETAIL: null,

    // states
    STATE_VENDOR_PRODUCT_LIST: null,
    STATE_VENDOR_PRODUCT_NEW: null,
    STATE_VENDOR_PRODUCT_EDIT: null,
    STATE_VENDOR_PRODUCT_DETAIL: null,
    STATE_VENDOR_PRODUCT_SETTING: null,
    STATE_VENDOR_PRODUCT_SETTING_EDIT: null,
    STATE_VENDOR_PRODUCT_COMMENT: null,

});
