var keyMirror = require('keymirror');

module.exports = keyMirror({
    // actions
    ACTION_VENDOR_PRODUCT_LIST_TRIGGER_DETAIL: null,
    ACTION_VENDOR_PRODUCT_LIST_TRIGGER_SETTING: null,
    ACTION_VENDOR_PRODUCT_LIST_TRIGGER_NEW: null,
    ACTION_VENDOR_PRODUCT_LIST_TRIGGER_AGREEMENT: null,
    ACTION_VENDOR_PRODUCT_LIST_TRIGGER_GUIDE: null,
    ACTION_VENDOR_PRODUCT_LIST_LOAD_LIST_SUCCESSFUL: null,
    ACTION_VENDOR_PRODUCT_LIST_LOAD_LIST_FAIL: null,
    ACTION_VENDOR_PRODUCT_LIST_LOAD_META_SUCCESSFUL: null,
    ACTION_VENDOR_PRODUCT_LIST_LOAD_META_FAIL: null,
    ACTION_VENDOR_PRODUCT_LIST_LOAD_SESSION_SUCCESSFUL: null,
    ACTION_VENDOR_PRODUCT_LIST_LOAD_SESSION_FAIL: null,
    ACTION_VENDOR_PRODUCT_LIST_LOAD_VENDOR_SUCCESSFUL: null,
    ACTION_VENDOR_PRODUCT_LIST_LOAD_VENDOR_FAIL: null,
    ACTION_VENDOR_PRODUCT_LIST_LOAD_EXAMPLE_SUCCESSFUL: null,
    ACTION_VENDOR_PRODUCT_LIST_LOAD_EXAMPLE_FAIL: null,

    ACTION_VENDOR_PRODUCT_DETAIL_TRIGGER_LIST: null,
    ACTION_VENDOR_PRODUCT_DETAIL_TRIGGER_EDIT: null,
    ACTION_VENDOR_PRODUCT_DETAIL_TRIGGER_PREVIEW: null,
    ACTION_VENDOR_PRODUCT_DETAIL_TRIGGER_PREVIEW_FAIL: null,
    ACTION_VENDOR_PRODUCT_DETAIL_TRIGGER_COMMENT: null,
    ACTION_VENDOR_PRODUCT_DETAIL_LOAD_DETAIL_SUCCESSFUL: null,
    ACTION_VENDOR_PRODUCT_DETAIL_LOAD_DETAIL_FAIL: null,
    ACTION_VENDOR_PRODUCT_DETAIL_PUBLISH: null,
    ACTION_VENDOR_PRODUCT_DETAIL_WITHDRAW: null,

    ACTION_VENDOR_PRODUCT_COMMENT_TRIGGER_DETAIL: null,
    ACTION_VENDOR_PRODUCT_COMMENT_LOAD_DATA_SUCCESSFUL: null,
    ACTION_VENDOR_PRODUCT_COMMENT_LOAD_DATA_FAIL: null,

    ACTION_VENDOR_PRODUCT_SETTING_TRIGGER_SETTING_EDIT: null,
    ACTION_VENDOR_PRODUCT_SETTING_TRIGGER_LIST: null,
    ACTION_VENDOR_PRODUCT_SETTING_LOAD_DATA_SUCCESSFUL: null,
    ACTION_VENDOR_PRODUCT_SETTING_LOAD_DATA_FAIL: null,
    ACTION_VENDOR_PRODUCT_SETTING_SAVE_DATA_SUCCESSFUL: null,
    ACTION_VENDOR_PRODUCT_SETTING_SAVE_DATA_FAIL: null,

    ACTION_VENDOR_PRODUCT_SETTING_EDIT_SAVE_TRIGGER_SETTING: null,
    ACTION_VENDOR_PRODUCT_SETTING_EDIT_CANCEL_TRIGGER_SETTING: null,
    ACTION_VENDOR_PRODUCT_SETTING_EDIT_SAVE_DATA_SUCCESSFUL: null,
    ACTION_VENDOR_PRODUCT_SETTING_EDIT_SAVE_DATA_FAIL: null,
    ACTION_VENDOR_PRODUCT_SETTING_EDIT_SHOW_VERIFY_MSG: null,

    ACTION_VENDOR_PRODUCT_NEW_SAVE_TRIGGER_DETAIL: null,
    ACTION_VENDOR_PRODUCT_NEW_CANCEL_TRIGGER_LIST: null,
    ACTION_VENDOR_PRODUCT_NEW_SAVE_DATA_SUCCESS: null,
    ACTION_VENDOR_PRODUCT_NEW_SAVE_DATA_FAIL: null,

    ACTION_VENDOR_PRODUCT_EDIT_SAVE_TRIGGER_DETAIL: null,
    ACTION_VENDOR_PRODUCT_EDIT_CANCEL_TRIGGER_DETAIL: null,
    ACTION_VENDOR_PRODUCT_EDIT_DELETE_TRIGGER_LIST: null,
    ACTION_VENDOR_PRODUCT_EDIT_SAVE_DATA_SUCCESSFUL: null,
    ACTION_VENDOR_PRODUCT_EDIT_SAVE_DATA_FAIL: null,
    ACTION_VENDOR_PRODUCT_EDIT_DELETE_DATA_SUCCESSFUL: null,
    ACTION_VENDOR_PRODUCT_EDIT_DELETE_DATA_FAIL: null,
    ACTION_VENDOR_PRODUCT_EDIT_SHOW_VERIFY_MSG: null,

    ACTION_VENDOR_PRODUCT_AGREEMENT_AGREE_TRIGGER_LIST: null,
    ACTION_VENDOR_PRODUCT_AGREEMENT_CANCEL_TRIGGER_LIST: null,
    ACTION_VENDOR_PRODUCT_AGREEMENT_AGREE_SUCCESSFUL: null,
    ACTION_VENDOR_PRODUCT_AGREEMENT_AGREE_FAIL: null,

    ACTION_VENDOR_PRODUCT_GUIDE_TRIGGER_LIST: null,

    ACTION_GET_WX_SIGNATURE_SUCCESS: null,
    ACTION_GET_WX_SIGNATURE_FAIL: null,
    ACTION_GET_WX_MEDIA_SUCCESS: null,
    ACTION_GET_WX_MEDIA_FAIL: null,



    // states
    STATE_VENDOR_PRODUCT_LIST: null,
    STATE_VENDOR_PRODUCT_LIST_JOIN: null,
    STATE_VENDOR_PRODUCT_LIST_AGREEMENT: null,
    STATE_VENDOR_PRODUCT_LIST_WELCOME: null,
    STATE_VENDOR_PRODUCT_LIST_ERR: null,
    STATE_VENDOR_PRODUCT_NEW: null,
    STATE_VENDOR_PRODUCT_EDIT: null,
    STATE_VENDOR_PRODUCT_DETAIL: null,
    STATE_VENDOR_PRODUCT_SETTING: null,
    STATE_VENDOR_PRODUCT_SETTING_EDIT: null,
    STATE_VENDOR_PRODUCT_COMMENT: null,
    STATE_VENDOR_PRODUCT_PREVIEW: null,
    STATE_VENDOR_PRODUCT_AGREEMENT: null,
    STATE_VENDOR_PRODUCT_GUIDE: null,

});
