var keyMirror = require('keymirror');

module.exports = keyMirror({
    // actions
    HIDOGS_VENDOR_PRODUCT_VIEW_PRODUCT_LIST: null,
    HIDOGS_VENDOR_PRODUCT_GET_PRODUCT_LIST: null,
    HIDOGS_VENDOR_PRODUCT_GET_PRODUCT_LIST_SUCCESS: null,
    HIDOGS_VENDOR_PRODUCT_GET_PRODUCT_LIST_FAIL: null,

    HIDOGS_VENDOR_PRODUCT_VIEW_PRODUCT: null,
    HIDOGS_VENDOR_PRODUCT_GET_PRODUCT_SUCCESS: null,
    HIDOGS_VENDOR_PRODUCT_GET_PRODUCT_FAIL: null,

    HIDOGS_VENDOR_PRODUCT_VIEW_PRODUCT_NEW: null,
    HIDOGS_VENDOR_PRODUCT_NEW_PRODUCT: null,
    HIDOGS_VENDOR_PRODUCT_NEW_PRODUCT_SUCCESS: null,
    HIDOGS_VENDOR_PRODUCT_NEW_PRODUCT_FAIL: null,

    HIDOGS_VENDOR_PRODUCT_META_PRODUCT_SUCCESS: null,
    HIDOGS_VENDOR_PRODUCT_META_PRODUCT_FAIL: null,

    HIDOGS_VENDOR_PRODUCT_VIEW_PRODUCT_DELETE: null,
    HIDOGS_VENDOR_PRODUCT_DELETE_PRODUCT: null,
    HIDOGS_VENDOR_PRODUCT_DELETE_PRODUCT_SUCCESS: null,
    HIDOGS_VENDOR_PRODUCT_DELETE_PRODUCT_FAIL: null,

    HIDOGS_VENDOR_PRODUCT_VIEW_PRODUCT_EDIT: null,
    HIDOGS_VENDOR_PRODUCT_EDIT_PRODUCT: null,
    HIDOGS_VENDOR_PRODUCT_EDIT_PRODUCT_SUCCESS: null,
    HIDOGS_VENDOR_PRODUCT_EDIT_PRODUCT_FAIL: null,

    // states
    VENDOR_PRODUCT_STORE_STATE_LIST: null,
    VENDOR_PRODUCT_STORE_STATE_LIST_LOADING: null,
    VENDOR_PRODUCT_STORE_STATE_PRODUCT: null,
    VENDOR_PRODUCT_STORE_STATE_EDIT: null,
    VENDOR_PRODUCT_STORE_STATE_NEW: null,
    VENDOR_PRODUCT_STORE_STATE_DELETE: null,
    VENDOR_PRODUCT_STORE_STATE_ERROR: null,

    // pictures
    UPLOAD_FILE_SUCCESS: null,
    UPLOAD_FILE_FAIL: null,
    REMOVE_FILE: null,

});
