var keyMirror = require('keymirror');

module.exports = keyMirror({
    // actions
    ACTION_GET_COUPON_LIST_SUCCESS: null,
    ACTION_GET_COUPON_LIST_FAIL: null,

    ACTION_LOAD_USER_SUCCESSFUL: null,
    ACTION_LOAD_VENDOR_SUCCESSFUL: null,
    ACTION_LOAD_PRODUCT_SUCCESSFUL: null,
    ACTION_LOAD_USER_VENDOR_PRODUCT_FAIL: null,

    ACITON_TRIGGER_NEW_FROM_LIST: null,
    ACITON_TRIGGER_DETAIL_FROM_LIST: null,

    ACITON_TRIGGER_LIST_FROM_NEW: null,
    ACITON_TRIGGER_DETAIL_FROM_NEW: null,
    ACTION_SUBMIT_NEW_SUCCESSFUL: null,
    ACTION_SUBMIT_NEW_FAIL: null,

    ACITON_TRIGGER_LIST_FROM_DETAIL: null,
    ACITON_TRIGGER_EDIT_FROM_DETAIL: null,

    ACITON_TRIGGER_DETAIL_SUBMIT_FROM_EDIT: null,
    ACITON_TRIGGER_DETAIL_CANCEL_FROM_EDIT: null,
    ACTION_SUBMIT_UPDATE_SUCCESSFUL: null,
    ACTION_SUBMIT_UPDATE_FAIL: null,

    ACTION_VERIFY: null,

    // states
    STATE_LIST: null,
    STATE_NEW: null,
    STATE_EDIT: null,
    STATE_DETAIL: null,

});
